#include "game.h"
#include "levelone_logic.h"
#include "leveltwo_logic.h"
#include "sfx.h"

#include "tileset.h"
#include "levelone.h"
#include "collisionMapOne.h"

void initLevel1(void) {
    int i;

    initMode0();

    // BG0 = HUD
    setupBackground(0, BG_PRIORITY(0) | BG_CHARBLOCK(HUD_CHARBLOCK) | BG_SCREENBLOCK(HUD_SCREENBLOCK) | BG_4BPP | BG_SIZE_SMALL);

    // BG1 = gameplay map
    setupBackground(1, BG_PRIORITY(1) | BG_CHARBLOCK(LEVEL_CHARBLOCK) | BG_SCREENBLOCK(LEVEL_SCREENBLOCK) | BG_4BPP | BG_SIZE_SMALL);

    // Load gameplay palette and tiles back into BG memory
    loadBgPalette(tilesetPal, tilesetPalLen / 2);
    BG_PALETTE[240] = BLACK;
    BG_PALETTE[241] = WHITE;
    loadTilesToCharblock(LEVEL_CHARBLOCK, tilesetTiles, tilesetTilesLen / 2);

    level1HOff = 0;
    level1VOff = 0;
    setBackgroundOffset(0, 0, 0);
    setBackgroundOffset(1, level1HOff, level1VOff);

    buildLevel1MapAndCollision();

    player.lives = 3;
    player.invincibleTimer = 0;
    resetPlayerForCurrentLevel();

    enemiesRemaining = MAX_ENEMIES;
    doorVisible = 0;
    doorOpen = 0;

    for (i = 0; i < MAX_PLAYER_BULLETS; i++) {
        playerBullets[i].active = 0;
        playerBullets[i].width = 8;
        playerBullets[i].height = 8;
    }

    for (i = 0; i < MAX_ENEMY_BULLETS; i++) {
        enemyBullets[i].active = 0;
        enemyBullets[i].width = 8;
        enemyBullets[i].height = 8;
    }

    for (i = 0; i < MAX_ENEMIES; i++) {
        enemies[i].width = 16;
        enemies[i].height = 16;
        enemies[i].active = 1;
        enemies[i].shootTimer = 30 + i * 15;
        enemies[i].animCounter = 0;
        enemies[i].currentFrame = 0;
        enemies[i].phase = ENEMY_FLOATING;
    }

    enemies[0].x = 72;
    enemies[0].y = 52;
    enemies[0].xVel = 1;
    enemies[0].minX = 56;
    enemies[0].maxX = 112;
    enemies[0].direction = DIR_RIGHT;

    enemies[1].x = 152;
    enemies[1].y = 84;
    enemies[1].xVel = 1;
    enemies[1].minX = 136;
    enemies[1].maxX = 200;
    enemies[1].direction = DIR_LEFT;

    enemies[2].x = 112;
    enemies[2].y = 176;
    enemies[2].xVel = 1;
    enemies[2].minX = 88;
    enemies[2].maxX = 168;
    enemies[2].direction = DIR_RIGHT;

    enemies[3].x = 208;
    enemies[3].y = 112;
    enemies[3].xVel = 1;
    enemies[3].minX = 184;
    enemies[3].maxX = 232;
    enemies[3].direction = DIR_LEFT;

    for (i = 0; i < MAX_BALLOONS; i++) {
        balloons[i].active = 0;
        balloons[i].width = 24;
        balloons[i].height = 24;
        balloons[i].spriteVariant = nextRandomSpriteVariant();
    }

    balloons[0].x = 36;  balloons[0].y = 144; balloons[0].active = 1;
    balloons[1].x = 88;  balloons[1].y = 152; balloons[1].active = 1;
    balloons[2].x = 126; balloons[2].y = 88;  balloons[2].active = 1;
    balloons[3].x = 168; balloons[3].y = 136; balloons[3].active = 1;
    balloons[4].x = 220; balloons[4].y = 72;  balloons[4].active = 1;
    balloons[5].x = 232; balloons[5].y = 168; balloons[5].active = 1;
}

void buildLevel1MapAndCollision(void) {
    int x;
    int y;

    // Copy the artist-made level 1 tilemap generated by grit/usenti
    // This preserves the full background artwork instead of replacing it with simple tiles.
    DMANow(3, (void*) leveloneMap, SCREENBLOCK[LEVEL_SCREENBLOCK].tilemap, leveloneLen / 2);

    // The level 1 collision data comes from collisionMapOneBitmap in collisionMapOne.h.
    // We use that bitmap for all collision checks through getCollisionPixel().
    (void)collisionMapOneBitmap;

    // Door position stays the same. It becomes visible after all enemies are defeated.
    // GO HERE TO UPDAYE DOOR LOCATION
    doorX = 225;
    doorY = 192;

    // No manual collision grid build is needed because the bitmap already defines collision.
    // Leave this function in place so the rest of the game can still call it the same way.
    for (y = 0; y < 1; y++) {
        for (x = 0; x < 1; x++) {
            // Intentionally empty.
        }
    }
}

void updateLevel1(void) {
    if (BUTTON_PRESSED(BUTTON_START)) {
        pausedState = STATE_LEVEL1;
        state = STATE_PAUSE;
        menuNeedsRedraw = 1;
        return;
    }

    if (player.invincibleTimer > 0) {
        player.invincibleTimer--;
    }

    updatePlayerLevel1();
    updatePlayerBullets();
    updateEnemyBullets();
    updateEnemies();
    updateBalloonsLevel1();
    updatePlayerAnimation();

    level1HOff = CLAMP(player.x - (SCREENWIDTH / 2) + (player.width / 2), 0, LEVEL1_PIXEL_W - SCREENWIDTH);
    level1VOff = CLAMP(player.y - (SCREENHEIGHT / 2), 0, LEVEL1_PIXEL_H - SCREENHEIGHT);
    setBackgroundOffset(1, level1HOff, level1VOff);

    if (enemiesRemaining <= 0 && !doorVisible) {
        doorVisible = 1;
        sfxDoorAppear();
    }

    if (doorVisible) {
        // Door is 32x32 pixels (4 tiles wide x 4 tiles tall)
        if (collision(player.x, player.y, player.width, player.height,
                      doorX, doorY, 32, 32)) {
            if (!doorOpen) {
                // First contact: open the door
                doorOpen = 1;
                sfxDoorOpen();
            } else {
                // Second contact while open: enter and advance to level 2
                sfxDoorEnter();
                state = STATE_LEVEL2_INTRO;
                menuNeedsRedraw = 1;
                return;
            }
        }
    }

    if (player.lives <= 0) {
        state = STATE_LOSE;
        menuNeedsRedraw = 1;
    }
}

void updatePlayerLevel1(void) {
    int nextX;
    int floatStrength;

    // Save old position
    player.oldX = player.x;
    player.oldY = player.y;

    // Default movement state
    player.isMoving = 0;

    // Horizontal movement
    // Move left with a small step-up assist for bridge/platform edges.
    if (BUTTON_HELD(BUTTON_LEFT)) {
        int i;
        int steppedUp = 0;
        for (i = 0; i < 2; i++) {
            nextX = player.x - 1;

            if (canMoveTo(nextX, player.y, player.width, player.height)) {
                player.x = nextX;
            } else if (player.grounded && !steppedUp &&
                       canMoveTo(nextX, player.y - 1, player.width, player.height)) {
                // Only step up once per frame and only when grounded on a platform edge.
                player.x = nextX;
                player.y -= 1;
                steppedUp = 1;
            } else {
                break;
            }
        }

        player.direction = DIR_LEFT;
        player.isMoving = 1;
    }

    if (BUTTON_HELD(BUTTON_RIGHT)) {
        int i;
        int steppedUp = 0;
        for (i = 0; i < 2; i++) {
            nextX = player.x + 1;

            if (canMoveTo(nextX, player.y, player.width, player.height)) {
                player.x = nextX;
            } else if (player.grounded && !steppedUp &&
                       canMoveTo(nextX, player.y - 1, player.width, player.height)) {
                // Only step up once per frame and only when grounded on a platform edge.
                player.x = nextX;
                player.y -= 1;
                steppedUp = 1;
            } else {
                break;
            }
        }

        player.direction = DIR_RIGHT;
        player.isMoving = 1;
    }

    // Check whether the player is standing on solid ground
    if (!canMoveTo(player.x, player.y + 1, player.width, player.height)) {
        player.grounded = 1;
    } else {
        player.grounded = 0;
    }

    // Press A to float/jump upward.
    //
    // Each press gives an upward impulse based on remaining lives.
    // More lives = stronger float height.
    //
    // This still works both on the ground and in the air, so the player can
    // float upward repeatedly as long as they still have lives remaining.
    if (BUTTON_PRESSED(BUTTON_UP) && player.lives > 0) {
        player.yVel = getFloatVelocityForLives(player.lives);

        // Give the jump/float a short multi-frame boost window so the motion
        // feels more curved and natural instead of looking like a single-frame
        // pop upward.
        player.floatBoostTimer = player.lives + 1;

        player.grounded = 0;
        player.isMoving = 1;
    }

    // A held = fly upward.
    //
    // This is more reliable than a one-frame BUTTON_PRESSED impulse and matches
    // the intended "float/fly upward" behavior much better.
    //
    // More lives = stronger upward speed:
    // 3 lives -> fastest upward
    // 2 lives -> medium upward
    // 1 life  -> weakest upward
    //
    // This works both from the ground and in the air.
    if (BUTTON_HELD(BUTTON_UP) && player.lives > 0) {
        int targetUpVel = getFloatVelocityForLives(player.lives);

        // Start flying if grounded.
        player.grounded = 0;
        player.isMoving = 1;

        // While A is held, keep pulling velocity upward toward the target.
        // This makes the movement feel smooth and controllable instead of
        // acting like a tiny single-frame hop.
        if (player.yVel > targetUpVel) {
            player.yVel--;
        }

        // Clamp so we do not fly upward faster than intended for this
        // number of lives.
        if (player.yVel < targetUpVel) {
            player.yVel = targetUpVel;
        }
    } else {
        // When A is not being held, gravity takes over normally.
        if (!player.grounded) {
            player.yVel += PLAYER_GRAVITY;

            if (player.yVel > PLAYER_MAX_FALL_SPEED) {
                player.yVel = PLAYER_MAX_FALL_SPEED;
            }
        }
    }

    // If grounded, do not keep downward falling speed.
    if (player.grounded && player.yVel > 0) {
        player.yVel = 0;
    }

    // This older boost timer behavior is no longer needed because flying is
    // now driven directly by holding A.
    player.floatBoostTimer = 0;

    // Apply vertical velocity one pixel at a time for smoother collision handling
    while (player.yVel < 0) {
        if (canMoveTo(player.x, player.y - 1, player.width, player.height)) {
            player.y--;
            player.yVel++;
        } else {
            player.yVel = 0;
            break;
        }
    }

    while (player.yVel > 0) {
        if (canMoveTo(player.x, player.y + 1, player.width, player.height)) {
            player.y++;
            player.yVel--;
        } else {
            player.yVel = 0;
            break;
        }
    }

    // Recompute grounded state after vertical movement
    if (!canMoveTo(player.x, player.y + 1, player.width, player.height)) {
        player.grounded = 1;
        if (player.yVel > 0) {
            player.yVel = 0;
        }
    } else {
        player.grounded = 0;
    }

    // Keep player inside the map bounds
    player.x = CLAMP(player.x, 0, LEVEL1_PIXEL_W - player.width);
    player.y = CLAMP(player.y, 0, LEVEL1_PIXEL_H - player.height);

    // Hazard check
    if (rectTouchesColor(player.x, player.y, player.width, player.height, CM_KILL)) {
        damagePlayer();
    }

    // Fire with B
    if (BUTTON_PRESSED(BUTTON_B)) {
        firePlayerBullet();
    }

    // Floating looks nicer if the player animation is treated as moving when drifting
    floatStrength = absInt(player.y - player.oldY);
    if (floatStrength > 0) {
        player.isMoving = 1;
    }
}

void updateBalloonsLevel1(void) {
    int i;

    for (i = 0; i < MAX_BALLOONS; i++) {
        if (!balloons[i].active) {
            continue;
        }

        if (collision(player.x, player.y, player.width, player.height,
                      balloons[i].x, balloons[i].y, balloons[i].width, balloons[i].height)) {

            balloons[i].active = 0;

            // Collecting a balloon always awards points — same behaviour whether
            // or not the player also gains a life.
            score += SCORE_BALLOON_BONUS;

            if (player.lives < 3) {
                player.lives++;
            }

            sfxBalloon();
        }
    }
}

void drawLevel1(void) {
    drawHUD();
    drawSpritesLevel1();
}

void drawSpritesLevel1(void) {
    int oamIndex = 0;
    int i;

    // Player
    drawPlayerSprite(player.x - level1HOff, player.y - level1VOff);
    oamIndex = 1;

    // Enemies
    for (i = 0; i < MAX_ENEMIES; i++) {
        if (enemies[i].active) {
            drawEnemySprite(i, oamIndex, enemies[i].x - level1HOff, enemies[i].y - level1VOff);            oamIndex++;
        }
    }

    // Player bullets
    for (i = 0; i < MAX_PLAYER_BULLETS; i++) {
        if (playerBullets[i].active) {
            drawBulletSprite(oamIndex, playerBullets[i].x - level1HOff, playerBullets[i].y - level1VOff, 0);
            oamIndex++;
        }
    }

    // Enemy bullets
    for (i = 0; i < MAX_ENEMY_BULLETS; i++) {
        if (enemyBullets[i].active) {
            drawBulletSprite(oamIndex, enemyBullets[i].x - level1HOff, enemyBullets[i].y - level1VOff, 1);
            oamIndex++;
        }
    }

    // Balloons
    for (i = 0; i < MAX_BALLOONS; i++) {
        if (balloons[i].active) {
            drawBalloonSprite(oamIndex, balloons[i].x - level1HOff, balloons[i].y - level1VOff, balloons[i].spriteVariant);
            oamIndex++;
        }
    }

    // Door after all enemies are defeated
    if (doorVisible) {
        drawDoorSprite(doorX - level1HOff, doorY - level1VOff);
        oamIndex++;
    }

    // Hide all remaining sprites
    hideUnusedSpritesFrom(oamIndex);

    // Copy shadow OAM to hardware OAM
    DMANow(3, shadowOAM, OAM, 512);
}